version: '3.7'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_USER=yourusername
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=gestion_reservas
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=yourusername
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=gestion_reservas
    ports:
      - "5432:5432"
